version: '3'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    hostname: 'ec2-3-88-32-126.compute-1.amazonaws.com'
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - ./mongodata:/data/db

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
     - 8081:8081
    hostname: 'ec2-3-88-32-126.compute-1.amazonaws.com'
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb 